version: "3"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: express-boilerplate
            POSTGRES_PASSWORD: express-boilerplate
            POSTGRES_DB: express-boilerplate
